export const SYSTEM_NAME = "SYSTEM_NAME";

export const SET_LOGIN_LOGOUT = "SET_LOGIN_LOGOUT";

export const SET_NOTIFY_MESSAGE = "SET_NOTIFY_MESSAGE";

export const SET_MOTIVE_QUOTE = "SET_MOTIVE_QUOTE";

export const SET_SENSOR_DATA = "SET_SENSOR_DATA";